services:
  db:
    image: postgres:14
    container_name: database
    environment:
      - POSTGRES_USER=Intro
      - POSTGRES_PASSWORD=contraseña_database
      - POSTGRES_DB=Skins_cs
      - DATABASE_URL=postgresql://Intro:contraseña_database@db:5432/Skins_cs
    ports:
      - 5432:5432
    volumes:
      - ./backend/psql_data:/var/lib/postgresql/data

